service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  profile: awsLearning
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:CreateTable
      Resource: '*'

functions:
  getProducts:
    handler: handlers/getProducts.getProductsHandler
    events:
      - httpApi:
          path: /products
          method: get
  getProductById:
    handler: handlers/getProductById.getProductByIdHandler
    events:
      - httpApi:
          path: /product/{id}
          method: get
  createProduct:
    handler: handlers/createProduct.createProductHandler
    events:
      - httpApi:
          path: /products
          method: post